export const ILL_TYPES = [1, 2, 3];
export const ILL_FREQUENCIES = [0.5, 0.1, 0.4];
export const ILL_DELAYS = [15, 40, 30];

export const CREATOR_NAME = "New Ill";
export const CREATOR_DELAY = 15;

export const REGISTRATION_PROCESS_NAME = "Registration";
export const REGISTRATION_PROCESS_DELAY_MEAN = 15;
export const REGISTRATION_CHANNELS_NUM = 2;

export const WARDS_TRANSFER_PROCESS_NAME = "Wards Transfer";
export const WARDS_TRANSFER_PROCESS_DELAY_MEAN = 3;
export const WARDS_TRANSFER_PROCESS_CHANNELS_NUM = 8;
export const WARDS_TRANSFER_DELAY_DEVIATION = 3;

export const LABORATORY_TRANSFER_PROCESS_NAME = "Laboratory Transfer";
export const LABORATORY_TRANSFER_DELAY_MEAN = 2;
export const LABORATORY_TRANSFER_CHANNELS_NUM = 5;
export const LABORATORY_TRANSFER_DELAY_DEVIATION = 100;

export const LABORATORY_REGISTRATION_PROCESS_NAME = "Laboratory Registration";
export const LABORATORY_REGISTRATION_PROCESS_DELAY_MEAN = 4.5;
export const LABORATORY_REGISTRATION_PROCESS_CHANNELS_NUM = 3;
export const LABORATORY_REGISTRATION_PROCESS_DELAY_DEVIATION = 1;

export const LABORATORY_ANALYSIS_PROCESS_NAME = "Laboratory Analysis";
export const LABORATORY_ANALYSIS_PROCESS_DELAY_MEAN = 4;
export const LABORATORY_ANALYSIS_PROCESS_CHANNELS_NUM = 2;
export const LABORATORY_ANALYSIS_PROCESS_DELAY_DEVIATION = 2;

export const REGISTRATION_TRANSFER_PROCESS_NAME = "Registration Transfer";
export const REGISTRATION_TRANSFER_PROCESS_DELAY_MEAN = 2;
export const REGISTRATION_TRANSFER_CHANNELS_NUM = 5;
export const REGISTRATION_TRANSFER_DELAY_DEVIATION = 100;

export const WARDS_DESPOSE_NAME = "Despose [Type 1 & 2]";
export const LABORATORY_DESPOSE_NAME = "Despose [Type 3]";